/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.28.4-g214e613 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.28.4-g214e613"
#endif
#define SDL_REVISION_NUMBER 0
